--- #YAML:1.0
name:               Devel-Ladybug
version:            0.407
abstract:           ~
author:
    - Alex Ayars <pause@nodekit.org>
license:            open_source
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Cache::Memcached::Fast:  0.16
    Clone:                0.31
    Data::GUID:           0.045
    DBI:                  1.4
    DBIx::TextIndex:      0.28
    Error:                0.17015
    File::HomeDir:        0.86
    File::Tempdir:        0.02
    Math::VecStat:        0.08
    Rcs:                  1.05
    Test::Simple:         0.94
    URI:                  1.4
    YAML::Syck:           1.07
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
